DROP TABLE IF EXISTS step_history;
DROP TABLE IF EXISTS workflow_execution;

CREATE TABLE WORKFLOW_EXECUTION (
  ID VARCHAR(255) PRIMARY KEY,
  WORKFLOW_ID VARCHAR(255) NOT NULL,
  STATUS VARCHAR(50) NOT NULL,
  CURRENT_STEP INT NOT NULL,
  CONTEXT_JSON CLOB,
  VERSION INT NOT NULL
);

CREATE TABLE STEP_HISTORY (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  EXECUTION_ID VARCHAR(255) NOT NULL,
  STEP_NAME VARCHAR(255) NOT NULL,
  STATUS VARCHAR(50) NOT NULL,
  OUTPUT_JSON CLOB,
  SEQUENCE_ORDER INT NOT NULL
);